services:
  - type: web
    name: win-squares
    env: node
    plan: free
    buildCommand: npm install && npm --prefix client install && npm --prefix client run build
    startCommand: npm start
    autoDeploy: true
